const SUPABASE_URL='https://wmdqqxdyhqxfrtptqwjq.supabase.co';
const PIN_API=`${SUPABASE_URL}/functions/v1/bakul-pin-api`;
const state={session:null,categories:[],payments:[],items:[],historyPage:0,historyPageSize:30,lastHistory:[],dashboard:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>'Rp '+new Intl.NumberFormat('id-ID').format(Number(n||0));
const compact=n=>new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(Number(n||0));
const fmtDate=s=>{if(!s)return'-';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`};
const monthLabel=s=>new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(`${s}-01T12:00:00`));
const slugCategory=n=>({'Bahan Baku':'bahan_baku','Operasional':'operasional','Beban Lainnya':'beban_lainnya'}[n]||n);
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3000)}
function getSession(){try{return JSON.parse(localStorage.getItem('bakul_pin_session')||'null')}catch{return null}}
function saveSession(v){state.session=v;if(v)localStorage.setItem('bakul_pin_session',JSON.stringify(v));else localStorage.removeItem('bakul_pin_session')}
async function apiCall(action,payload={},allowAnonymous=false){const headers={'Content-Type':'application/json'};if(!allowAnonymous&&state.session?.token)headers.Authorization=`Bearer ${state.session.token}`;const r=await fetch(PIN_API,{method:'POST',headers,body:JSON.stringify({action,...payload})});let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===401&&!allowAnonymous){clearSession(false)}throw new Error(d.error||d.message||`HTTP ${r.status}`)}return d}
async function login(pin){const d=await apiCall('login',{pin},true);saveSession({token:d.token,expiresAt:d.expiresAt});return d}
function clearSession(show=true){saveSession(null);$('#app').classList.add('hidden');$('#login-view').classList.remove('hidden');if(show)toast('Anda telah keluar.')}
async function logout(show=true){const token=state.session?.token;try{if(token)await fetch(PIN_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'logout'})})}catch{}clearSession(show)}
async function bootstrap(){const d=await apiCall('bootstrap');state.categories=d.categories||[];state.payments=d.payments||[];state.items=d.items||[];populateSelects();$('#profile-email').textContent='Akses PIN';$('#sidebar-user-email').textContent='Administrator';$('#expense-date').value=new Date().toISOString().slice(0,10);const m=new Date().toISOString().slice(0,7);$('#dashboard-month').value=m;await Promise.all([loadDashboard(),loadMaster()]);}
function populateSelects(){const catOpts='<option value="">Semua kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#history-category').innerHTML=catOpts;$('#master-category').innerHTML=catOpts;$('#expense-category').innerHTML='<option value="">Pilih kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#new-item-category').innerHTML='<option value="">Pilih kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#expense-payment').innerHTML='<option value="">Pilih metode</option>'+state.payments.map(p=>`<option value="${p.code}">${escapeHtml(p.name)}</option>`).join('');filterExpenseItems()}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function navigate(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const meta={dashboard:['Ringkasan Pengeluaran','Pantau arus pengeluaran dan pola belanja dalam satu tampilan.'],input:['Input Pengeluaran','Catat transaksi baru secara aman dan realtime.'],history:['Riwayat Belanja','Telusuri seluruh transaksi yang tersimpan di Supabase.'],master:['Master Data Item','Kelola katalog item sebagai referensi transaksi.']}[page];$('#page-title').textContent=meta[0];$('#page-subtitle').textContent=meta[1];if(page==='history')loadHistory(true);if(page==='master')loadMaster();window.scrollTo({top:0,behavior:'smooth'})}
async function loadDashboard(){const month=$('#dashboard-month').value||new Date().toISOString().slice(0,7);$('#refresh-dashboard').disabled=true;try{const d=await apiCall('dashboard',{month});state.dashboard=d;renderDashboard(d);$('#dashboard-period').textContent=`Ringkasan ${monthLabel(month)}`}catch(e){toast(e.message,true)}finally{$('#refresh-dashboard').disabled=false}}
function renderDashboard(d){const cat=d.categoryTotals||[];const cards=[{label:'Total Pengeluaran',value:rupiah(d.totalExpense),hint:`${d.transactionCount} transaksi`,icon:'↗',hero:true},{label:'Rata-rata Transaksi',value:rupiah(d.averageTransaction),hint:'Nilai rata-rata per transaksi',icon:'≈'},...cat.slice(0,2).map((c,i)=>({label:c.name,value:rupiah(c.total),hint:`${c.transaction_count||0} transaksi`,icon:i?'◇':'⌁'}))];$('#kpi-grid').innerHTML=cards.map(c=>`<article class="kpi-card ${c.hero?'hero':''}"><div class="kpi-top"><small>${escapeHtml(c.label)}</small><div class="kpi-icon">${c.icon}</div></div><strong>${escapeHtml(c.value)}</strong><div class="kpi-hint">${escapeHtml(c.hint)}</div></article>`).join('');renderTrend(d.dailySeries||[]);renderPayments(d.paymentBreakdown||[],d.totalExpense);renderTop(d.topItems||[],d.totalExpense);$('#trend-total').textContent=rupiah(d.totalExpense)}
function renderTrend(rows){if(!rows.length){$('#trend-chart').innerHTML='<div class="empty">Belum ada transaksi pada periode ini.</div>';return}const w=760,h=230,pad=26,max=Math.max(...rows.map(r=>Number(r.total)),1);const pts=rows.map((r,i)=>{const x=pad+(i*(w-pad*2)/Math.max(rows.length-1,1));const y=h-pad-(Number(r.total)/max*(h-pad*2));return{x,y,r}});const line=pts.map(p=>`${p.x},${p.y}`).join(' ');const area=`${pad},${h-pad} ${line} ${pts.at(-1).x},${h-pad}`;const grids=[.25,.5,.75,1].map(q=>`<line class="chart-grid" x1="${pad}" y1="${h-pad-q*(h-pad*2)}" x2="${w-pad}" y2="${h-pad-q*(h-pad*2)}"/>`).join('');const dots=pts.map((p,i)=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="${i===pts.length-1?4:2.5}"><title>${fmtDate(p.r.date)} — ${rupiah(p.r.total)}</title></circle>`).join('');const labelPts=pts.filter((_,i)=>i===0||i===pts.length-1||i===Math.floor(pts.length/2));const labels=labelPts.map(p=>`<text class="chart-label" x="${p.x}" y="${h-4}" text-anchor="middle">${p.r.date.slice(8,10)}/${p.r.date.slice(5,7)}</text>`).join('');$('#trend-chart').innerHTML=`<svg class="chart-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#38bdf8" stop-opacity=".23"/><stop offset="1" stop-color="#38bdf8" stop-opacity="0"/></linearGradient></defs>${grids}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${line}"/>${dots}${labels}</svg>`}
function renderPayments(rows,total){const safe=Math.max(Number(total),1);$('#payment-breakdown').innerHTML=rows.filter(r=>Number(r.total)>0).map(r=>{const pct=Math.round(Number(r.total)/safe*100);return `<div class="payment-row"><div class="payment-copy"><span>${escapeHtml(r.name)}</span><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><strong>${rupiah(r.total)}</strong></div>`}).join('')||'<div class="empty">Belum ada data.</div>'}
function renderTop(rows,total){const max=Math.max(...rows.map(r=>Number(r.total)),1);$('#top-items').innerHTML=rows.map((r,i)=>`<div class="rank-row"><div class="rank-index">${String(i+1).padStart(2,'0')}</div><div class="rank-name"><strong>${escapeHtml(r.item)}</strong><span>${categoryName(r.category_code)} · ${r.transaction_count} transaksi</span></div><div class="rank-track"><i style="width:${Math.max(4,Number(r.total)/max*100)}%"></i></div><div class="rank-value">${rupiah(r.total)}</div></div>`).join('')||'<div class="empty">Belum ada data pada periode ini.</div>'}
function categoryName(code){return state.categories.find(c=>c.code===code)?.name||code}
function filterExpenseItems(){const cat=$('#expense-category').value;const q=$('#expense-item-search').value.trim().toLowerCase();const list=state.items.filter(i=>(!cat||i.category_code===cat)&&(!q||i.name.toLowerCase().includes(q))).slice(0,100);$('#expense-item').innerHTML='<option value="">Pilih item</option>'+list.map(i=>`<option value="${i.id}">${escapeHtml(i.name)}</option>`).join('')}
async function saveExpense(e){e.preventDefault();const btn=$('#save-expense');btn.disabled=true;try{const cleanPrice=Number($('#expense-total').value.replace(/\D/g,''));await apiCall('create_transaction',{date:$('#expense-date').value,itemId:$('#expense-item').value,qty:Number($('#expense-qty').value),unit:$('#expense-unit').value.trim()||'',paymentCode:$('#expense-payment').value,totalPrice:cleanPrice});toast('Pengeluaran berhasil disimpan ke Supabase.');e.target.reset();$('#expense-date').value=new Date().toISOString().slice(0,10);filterExpenseItems();await loadDashboard()}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
async function loadHistory(reset=false){if(reset)state.historyPage=0;const cat=$('#history-category').value,date=$('#history-date').value,q=$('#history-search').value.trim();try{const d=await apiCall('history',{page:state.historyPage,pageSize:state.historyPageSize,search:q,category:cat,dateFrom:date||'',dateTo:date||''});const rows=d.rows||[];state.lastHistory=rows;$('#history-body').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.transaction_no)}</strong></td><td>${fmtDate(r.transaction_date)}</td><td>${escapeHtml(r.item_name_snapshot)}</td><td><span class="badge">${escapeHtml(categoryName(r.category_code))}</span></td><td>${r.qty}${r.unit?' '+escapeHtml(r.unit):''}</td><td><span class="badge dark">${escapeHtml(state.payments.find(p=>p.code===r.payment_code)?.name||r.payment_code)}</span></td><td class="money">${rupiah(r.total_price)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Data tidak ditemukan.</td></tr>';$('#history-page-info').textContent=`Halaman ${state.historyPage+1}`;$('#history-prev').disabled=state.historyPage===0;$('#history-next').disabled=!d.hasMore}catch(e){toast(e.message,true)}}
function exportCsv(){const rows=state.lastHistory;if(!rows.length)return toast('Tidak ada data untuk diekspor.',true);const head=['ID','Tanggal','Kategori','Item','Qty','Satuan','Pembayaran','Total Harga'];const data=rows.map(r=>[r.transaction_no,r.transaction_date,categoryName(r.category_code),r.item_name_snapshot,r.qty,r.unit||'',state.payments.find(p=>p.code===r.payment_code)?.name||r.payment_code,r.total_price]);const csv=[head,...data].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`bakul-sayur-riwayat-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function loadMaster(){const q=$('#master-search')?.value.trim().toLowerCase()||'',cat=$('#master-category')?.value||'';const rows=state.items.filter(i=>(!cat||i.category_code===cat)&&(!q||`${i.legacy_item_id||''} ${i.name}`.toLowerCase().includes(q)));$('#master-body').innerHTML=rows.map(i=>`<tr><td>${escapeHtml(i.legacy_item_id||'—')}</td><td><strong>${escapeHtml(i.name)}</strong></td><td><span class="badge">${escapeHtml(categoryName(i.category_code))}</span></td><td>${escapeHtml(i.unit_default||'—')}</td><td><span class="badge success">Aktif</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Item tidak ditemukan.</td></tr>';const counts=state.categories.map(c=>({name:c.name,n:state.items.filter(i=>i.category_code===c.code).length}));$('#master-summary').innerHTML=counts.map(c=>`<div class="mini-kpi"><span>${escapeHtml(c.name.toUpperCase())}</span><strong>${c.n}</strong></div>`).join('')}
async function addItem(e){e.preventDefault();try{const cat=$('#new-item-category').value,name=$('#new-item-name').value.trim(),unit=$('#new-item-unit').value.trim()||'';const existing=state.items.some(i=>i.category_code===cat&&i.name.trim().toLowerCase()===name.toLowerCase());if(existing)throw new Error('Item dengan nama tersebut sudah ada pada kategori ini.');const created=await apiCall('create_item',{categoryCode:cat,name,unitDefault:unit});const item=Array.isArray(created)?created[0]:created;if(item)state.items.push(item);$('#item-dialog').close();e.target.reset();populateSelects();loadMaster();toast('Item baru berhasil ditambahkan.')}catch(err){toast(err.message,true)}}
function bind(){$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=$('#login-btn');b.disabled=true;try{await login($('#login-pin').value);$('#login-view').classList.add('hidden');$('#app').classList.remove('hidden');$('#login-pin').value='';await bootstrap()}catch(err){toast(err.message,true);$('#login-pin').select()}finally{b.disabled=false}});$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#logout-btn').addEventListener('click',()=>logout());$('#refresh-dashboard').addEventListener('click',loadDashboard);$('#dashboard-month').addEventListener('change',loadDashboard);$('#expense-category').addEventListener('change',filterExpenseItems);$('#expense-item-search').addEventListener('input',filterExpenseItems);$('#expense-item').addEventListener('change',()=>{const it=state.items.find(i=>i.id===$('#expense-item').value);if(it?.unit_default)$('#expense-unit').value=it.unit_default});$('#expense-total').addEventListener('input',e=>{const n=e.target.value.replace(/\D/g,'');e.target.value=n?new Intl.NumberFormat('id-ID').format(Number(n)):''});$('#expense-form').addEventListener('submit',saveExpense);['#history-search','#history-category','#history-date'].forEach(s=>$(s).addEventListener('input',()=>loadHistory(true)));$('#history-reset').addEventListener('click',()=>{$('#history-search').value='';$('#history-category').value='';$('#history-date').value='';loadHistory(true)});$('#history-prev').addEventListener('click',()=>{if(state.historyPage>0){state.historyPage--;loadHistory()}});$('#history-next').addEventListener('click',()=>{state.historyPage++;loadHistory()});$('#export-csv').addEventListener('click',exportCsv);['#master-search','#master-category'].forEach(s=>$(s).addEventListener('input',loadMaster));$('#open-add-item').addEventListener('click',()=>$('#item-dialog').showModal());$('#close-dialog').addEventListener('click',()=>$('#item-dialog').close());$('#cancel-item').addEventListener('click',()=>$('#item-dialog').close());$('#add-item-form').addEventListener('submit',addItem)}
async function init(){bind();state.session=getSession();const valid=state.session?.token&&state.session?.expiresAt&&new Date(state.session.expiresAt)>new Date();if(valid){$('#login-view').classList.add('hidden');$('#app').classList.remove('hidden');try{await bootstrap()}catch(e){toast(e.message,true);clearSession(false)}}else{clearSession(false);setTimeout(()=>$('#login-pin')?.focus(),120)}}
init();
