const SUPABASE_URL='https://nxnecmtlzfgududejput.supabase.co';
const PIN_API=`${SUPABASE_URL}/functions/v1/bakul-pin-api`;
const state={session:null,categories:[],payments:[],items:[],historyPage:0,historyPageSize:30,lastHistory:[],dashboard:null,syncing:false,currentPage:'dashboard',historySeq:0,dashboardSeq:0,readInflight:new Map(),installPrompt:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>'Rp '+new Intl.NumberFormat('id-ID').format(Number(n||0));
const compact=n=>new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(Number(n||0));
const fmtDate=s=>{if(!s)return'-';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`};
const monthLabel=s=>new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(`${s}-01T12:00:00`));
const slugCategory=n=>({'Bahan Baku':'bahan_baku','Operasional':'operasional','Beban Lainnya':'beban_lainnya'}[n]||n);
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3000)}
function getSession(){try{return JSON.parse(localStorage.getItem('bakul_pin_session')||'null')}catch{return null}}
function saveSession(v){state.session=v;if(v)localStorage.setItem('bakul_pin_session',JSON.stringify(v));else localStorage.removeItem('bakul_pin_session')}
const OFFLINE_DB='bakul-sayur-offline-v1';
let offlineDbPromise=null;
function openOfflineDb(){if(!('indexedDB'in window))return Promise.reject(new Error('IndexedDB tidak tersedia.'));if(offlineDbPromise)return offlineDbPromise;offlineDbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(OFFLINE_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('cache'))db.createObjectStore('cache');if(!db.objectStoreNames.contains('queue'))db.createObjectStore('queue',{keyPath:'id',autoIncrement:true})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return offlineDbPromise}
async function idbRequest(store,mode,run){const db=await openOfflineDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);const os=tx.objectStore(store);let req;try{req=run(os)}catch(e){reject(e);return}if(req){req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}else{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}})}
const cacheGet=key=>idbRequest('cache','readonly',s=>s.get(key)).catch(()=>null);
const cacheSet=(key,value)=>idbRequest('cache','readwrite',s=>s.put({value,savedAt:Date.now()},key)).catch(()=>null);
const cacheClear=()=>idbRequest('cache','readwrite',s=>s.clear()).catch(()=>null);
const queueAdd=(action,payload)=>idbRequest('queue','readwrite',s=>s.add({action,payload,createdAt:Date.now()}));
const queueList=()=>idbRequest('queue','readonly',s=>s.getAll()).catch(()=>[]);
const queueDelete=id=>idbRequest('queue','readwrite',s=>s.delete(id));
function cacheKey(action,payload={}){if(action==='bootstrap')return'bootstrap';if(action==='dashboard')return`dashboard:${payload.month||'current'}`;if(action==='history')return`history:${JSON.stringify(payload)}`;return null}
function networkError(error){return error instanceof TypeError||/fetch|network|offline|failed to fetch/i.test(String(error?.message||error))}
function debounce(fn,wait=220){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),wait)}}
async function updateConnectionStatus(){const pill=$('.status-pill');if(!pill)return;const pending=(await queueList()).length;const online=navigator.onLine;pill.classList.toggle('offline',!online);pill.classList.toggle('syncing',online&&pending>0);const label=pill.querySelector('span');if(label)label.textContent=!online?(pending?`Offline · ${pending} antre`:'Mode Offline'):(pending?`Sinkronisasi · ${pending} antre`:'Cloud tersinkron');document.body.classList.toggle('offline-mode',!online)}
async function apiCallOnline(action,payload={},allowAnonymous=false,signal=null){const headers={'Content-Type':'application/json'};if(!allowAnonymous&&state.session?.token)headers.Authorization=`Bearer ${state.session.token}`;const r=await fetch(PIN_API,{method:'POST',headers,body:JSON.stringify({action,...payload}),signal});let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===401&&!allowAnonymous){clearSession(false)}throw new Error(d.error||d.message||`HTTP ${r.status}`)}return d}
function refreshRead(action,payload,key){const sig=`${action}:${JSON.stringify(payload)}`;if(state.readInflight.has(sig))return state.readInflight.get(sig);const p=apiCallOnline(action,payload).then(async d=>{await cacheSet(key,d);return d}).finally(()=>state.readInflight.delete(sig));state.readInflight.set(sig,p);return p}
async function apiRead(action,payload={},onFresh=null){const key=cacheKey(action,payload);if(!key)return apiCallOnline(action,payload);const cached=await cacheGet(key);if(cached?.value){if(navigator.onLine)refreshRead(action,payload,key).then(d=>{onFresh?.(d);updateConnectionStatus()}).catch(()=>{});return cached.value}if(!navigator.onLine)throw new Error('Data ini belum tersimpan di perangkat. Hubungkan internet sekali untuk memuatnya.');const d=await refreshRead(action,payload,key);onFresh?.(d);return d}
async function apiCall(action,payload={},allowAnonymous=false){if(cacheKey(action,payload)&&!allowAnonymous)return apiRead(action,payload);if(action==='create_transaction'&&!allowAnonymous){if(!navigator.onLine){await queueAdd(action,payload);await updateConnectionStatus();return{queued:true}}try{return await apiCallOnline(action,payload)}catch(error){if(networkError(error)){await queueAdd(action,payload);await updateConnectionStatus();return{queued:true}}throw error}}return apiCallOnline(action,payload,allowAnonymous)}
async function syncPending(){if(state.syncing||!navigator.onLine||!state.session?.token)return;const rows=await queueList();if(!rows.length){updateConnectionStatus();return}state.syncing=true;await updateConnectionStatus();let synced=0;try{for(const row of rows){try{await apiCallOnline(row.action,row.payload);await queueDelete(row.id);synced++}catch(error){if(networkError(error)||/401|sesi/i.test(String(error?.message||error)))break;break}}if(synced){await cacheClear();toast(`${synced} transaksi offline berhasil disinkronkan.`);try{await bootstrap(true);if(state.currentPage==='history')await loadHistory(true,true)}catch(error){console.error(error)}}}finally{state.syncing=false;await updateConnectionStatus()}}
function registerServiceWorker(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js').then(reg=>reg.update().catch(()=>{})).catch(error=>console.error('Service worker error',error))}
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function syncInstallUI(){const installed=isStandalone();$('[data-install-app]').forEach(el=>el.classList.toggle('hidden',installed));$('#install-banner')?.classList.toggle('hidden',installed)}
function openInstallGuide(){const dialog=$('#install-dialog');if(!dialog)return;const title=$('#install-guide-title'),copy=$('#install-guide-copy'),steps=$('#install-guide-steps');if(isIOS()){title.textContent='Pasang Bakul Sayur di iPhone';copy.textContent='Tambahkan aplikasi ke Home Screen agar terbuka seperti aplikasi native.';steps.innerHTML='<li>Ketuk tombol <strong>Share</strong> di Safari.</li><li>Pilih <strong>Add to Home Screen</strong>.</li><li>Ketuk <strong>Add</strong>.</li>'}else{title.textContent='Pasang Bakul Sayur';copy.textContent='Gunakan menu browser jika prompt install otomatis belum tersedia.';steps.innerHTML='<li>Buka menu browser.</li><li>Pilih <strong>Install app</strong> atau <strong>Add to Home Screen</strong>.</li><li>Konfirmasi pemasangan.</li>'}dialog.showModal()}
async function handleInstall(){if(isStandalone())return toast('Bakul Sayur sudah terpasang.');if(state.installPrompt){const p=state.installPrompt;state.installPrompt=null;await p.prompt();const c=await p.userChoice;if(c?.outcome==='accepted')toast('Bakul Sayur sedang dipasang.');else syncInstallUI();return}openInstallGuide()}
function bindInstallEvents(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;syncInstallUI()});window.addEventListener('appinstalled',()=>{state.installPrompt=null;syncInstallUI();toast('Bakul Sayur berhasil dipasang.')});syncInstallUI()}
async function login(pin){const d=await apiCall('login',{pin},true);saveSession({token:d.token,expiresAt:d.expiresAt});return d}
function clearSession(show=true){saveSession(null);$('#app').classList.add('hidden');$('#login-view').classList.remove('hidden');if(show)toast('Anda telah keluar.')}
async function logout(show=true){const token=state.session?.token;try{if(token)await fetch(PIN_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'logout'})})}catch{}clearSession(show)}
function applyBootstrapData(d){state.categories=d.categories||[];state.payments=d.payments||[];state.items=d.items||[];populateSelects();$('#profile-email').textContent='Akses PIN';$('#sidebar-user-email').textContent='Administrator'}
async function bootstrap(force=false){const key=cacheKey('bootstrap',{});const d=force&&navigator.onLine?await refreshRead('bootstrap',{},key):await apiRead('bootstrap',{},applyBootstrapData);applyBootstrapData(d);if(!$('#expense-date').value)$('#expense-date').value=new Date().toISOString().slice(0,10);if(!$('#dashboard-month').value)$('#dashboard-month').value=new Date().toISOString().slice(0,7);await loadDashboard(force);loadMaster()}
function populateSelects(){const catOpts='<option value="">Semua kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#history-category').innerHTML=catOpts;$('#master-category').innerHTML=catOpts;$('#expense-category').innerHTML='<option value="">Pilih kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#new-item-category').innerHTML='<option value="">Pilih kategori</option>'+state.categories.map(c=>`<option value="${c.code}">${escapeHtml(c.name)}</option>`).join('');$('#expense-payment').innerHTML='<option value="">Pilih metode</option>'+state.payments.map(p=>`<option value="${p.code}">${escapeHtml(p.name)}</option>`).join('');filterExpenseItems()}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function navigate(page,{refresh=false}={}){if(!['dashboard','input','history','master'].includes(page))return;state.currentPage=page;$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));$('[data-page]').forEach(b=>{const active=b.dataset.page===page;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')});const meta={dashboard:['Ringkasan Pengeluaran','Pantau arus pengeluaran dan pola belanja dalam satu tampilan.'],input:['Input Pengeluaran','Catat transaksi cepat, bahkan saat koneksi terputus.'],history:['Riwayat Belanja','Telusuri transaksi dari cache lokal dan cloud.'],master:['Master Data Item','Kelola katalog item referensi transaksi.']}[page];$('#page-title').textContent=meta[0];$('#page-subtitle').textContent=meta[1];window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(()=>{if(page==='dashboard'&&(refresh||!state.dashboard))loadDashboard(refresh);if(page==='history'){loadHistory(true,refresh);window.loadHistorySummary?.(refresh)}if(page==='master')loadMaster()})}
async function loadDashboard(force=false){const month=$('#dashboard-month').value||new Date().toISOString().slice(0,7),seq=++state.dashboardSeq,btn=$('#refresh-dashboard');if(btn){btn.disabled=true;btn.classList.add('is-loading')}const apply=d=>{if(seq!==state.dashboardSeq)return;state.dashboard=d;renderDashboard(d);$('#dashboard-period').textContent=`Ringkasan ${monthLabel(month)}`};try{const key=cacheKey('dashboard',{month});const d=force&&navigator.onLine?await refreshRead('dashboard',{month},key):await apiRead('dashboard',{month},apply);apply(d)}catch(e){toast(e.message,true)}finally{if(seq===state.dashboardSeq&&btn){btn.disabled=false;btn.classList.remove('is-loading')}}}
function renderDashboard(d){const cat=d.categoryTotals||[];const cards=[{label:'Total Pengeluaran',value:rupiah(d.totalExpense),hint:`${d.transactionCount} transaksi`,icon:'↗',hero:true},{label:'Rata-rata Transaksi',value:rupiah(d.averageTransaction),hint:'Nilai rata-rata per transaksi',icon:'≈'},...cat.slice(0,2).map((c,i)=>({label:c.name,value:rupiah(c.total),hint:`${c.transaction_count||0} transaksi`,icon:i?'◇':'⌁'}))];$('#kpi-grid').innerHTML=cards.map(c=>`<article class="kpi-card ${c.hero?'hero':''}"><div class="kpi-top"><small>${escapeHtml(c.label)}</small><div class="kpi-icon">${c.icon}</div></div><strong>${escapeHtml(c.value)}</strong><div class="kpi-hint">${escapeHtml(c.hint)}</div></article>`).join('');renderTrend(d.dailySeries||[]);renderPayments(d.paymentBreakdown||[],d.totalExpense);renderTop(d.topItems||[],d.totalExpense);$('#trend-total').textContent=rupiah(d.totalExpense)}
function renderTrend(rows){if(!rows.length){$('#trend-chart').innerHTML='<div class="empty">Belum ada transaksi pada periode ini.</div>';return}const w=760,h=230,pad=26,max=Math.max(...rows.map(r=>Number(r.total)),1);const pts=rows.map((r,i)=>{const x=pad+(i*(w-pad*2)/Math.max(rows.length-1,1));const y=h-pad-(Number(r.total)/max*(h-pad*2));return{x,y,r}});const line=pts.map(p=>`${p.x},${p.y}`).join(' ');const area=`${pad},${h-pad} ${line} ${pts.at(-1).x},${h-pad}`;const grids=[.25,.5,.75,1].map(q=>`<line class="chart-grid" x1="${pad}" y1="${h-pad-q*(h-pad*2)}" x2="${w-pad}" y2="${h-pad-q*(h-pad*2)}"/>`).join('');const dots=pts.map((p,i)=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="${i===pts.length-1?4:2.5}"><title>${fmtDate(p.r.date)} — ${rupiah(p.r.total)}</title></circle>`).join('');const labelPts=pts.filter((_,i)=>i===0||i===pts.length-1||i===Math.floor(pts.length/2));const labels=labelPts.map(p=>`<text class="chart-label" x="${p.x}" y="${h-4}" text-anchor="middle">${p.r.date.slice(8,10)}/${p.r.date.slice(5,7)}</text>`).join('');$('#trend-chart').innerHTML=`<svg class="chart-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#4f9f72" stop-opacity=".23"/><stop offset="1" stop-color="#4f9f72" stop-opacity="0"/></linearGradient></defs>${grids}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${line}"/>${dots}${labels}</svg>`}
function renderPayments(rows,total){const safe=Math.max(Number(total),1);$('#payment-breakdown').innerHTML=rows.filter(r=>Number(r.total)>0).map(r=>{const pct=Math.round(Number(r.total)/safe*100);return `<div class="payment-row"><div class="payment-copy"><span>${escapeHtml(r.name)}</span><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><strong>${rupiah(r.total)}</strong></div>`}).join('')||'<div class="empty">Belum ada data.</div>'}
function renderTop(rows,total){const max=Math.max(...rows.map(r=>Number(r.total)),1);$('#top-items').innerHTML=rows.map((r,i)=>`<div class="rank-row"><div class="rank-index">${String(i+1).padStart(2,'0')}</div><div class="rank-name"><strong>${escapeHtml(r.item)}</strong><span>${categoryName(r.category_code)} · ${r.transaction_count} transaksi</span></div><div class="rank-track"><i style="width:${Math.max(4,Number(r.total)/max*100)}%"></i></div><div class="rank-value">${rupiah(r.total)}</div></div>`).join('')||'<div class="empty">Belum ada data pada periode ini.</div>'}
function categoryName(code){return state.categories.find(c=>c.code===code)?.name||code}
function filterExpenseItems(){const cat=$('#expense-category').value;const q=$('#expense-item-search').value.trim().toLowerCase();const list=state.items.filter(i=>(!cat||i.category_code===cat)&&(!q||i.name.toLowerCase().includes(q))).slice(0,100);$('#expense-item').innerHTML='<option value="">Pilih item</option>'+list.map(i=>`<option value="${i.id}">${escapeHtml(i.name)}</option>`).join('')}
async function saveExpense(e){e.preventDefault();const btn=$('#save-expense');btn.disabled=true;try{const cleanPrice=Number($('#expense-total').value.replace(/\D/g,''));const result=await apiCall('create_transaction',{date:$('#expense-date').value,itemId:$('#expense-item').value,qty:Number($('#expense-qty').value),unit:$('#expense-unit').value.trim()||'',paymentCode:$('#expense-payment').value,totalPrice:cleanPrice});toast(result?.queued?'Pengeluaran tersimpan di perangkat dan akan otomatis sinkron saat online.':'Pengeluaran berhasil disimpan ke cloud.');e.target.reset();$('#expense-date').value=new Date().toISOString().slice(0,10);filterExpenseItems();if(!result?.queued)await loadDashboard();await updateConnectionStatus()}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
function renderHistory(d,seq){if(seq!==state.historySeq)return;const rows=d.rows||[];state.lastHistory=rows;$('#history-body').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.transaction_no)}</strong></td><td>${fmtDate(r.transaction_date)}</td><td>${escapeHtml(r.item_name_snapshot)}</td><td><span class="badge">${escapeHtml(categoryName(r.category_code))}</span></td><td>${r.qty}${r.unit?' '+escapeHtml(r.unit):''}</td><td><span class="badge dark">${escapeHtml(state.payments.find(p=>p.code===r.payment_code)?.name||r.payment_code)}</span></td><td class="money">${rupiah(r.total_price)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Data tidak ditemukan.</td></tr>';$('#history-page-info').textContent=`Halaman ${state.historyPage+1}`;$('#history-prev').disabled=state.historyPage===0;$('#history-next').disabled=!d.hasMore}
async function loadHistory(reset=false,force=false){if(reset)state.historyPage=0;const seq=++state.historySeq,cat=$('#history-category').value,date=$('#history-date').value,q=$('#history-search').value.trim(),payload={page:state.historyPage,pageSize:state.historyPageSize,search:q,category:cat,dateFrom:date||'',dateTo:date||''};$('#history-body').classList.add('is-refreshing');try{const key=cacheKey('history',payload);const d=force&&navigator.onLine?await refreshRead('history',payload,key):await apiRead('history',payload,fresh=>renderHistory(fresh,seq));renderHistory(d,seq)}catch(e){if(seq===state.historySeq)toast(e.message,true)}finally{if(seq===state.historySeq)$('#history-body').classList.remove('is-refreshing')}}
function exportCsv(){const rows=state.lastHistory;if(!rows.length)return toast('Tidak ada data untuk diekspor.',true);const head=['ID','Tanggal','Kategori','Item','Qty','Satuan','Pembayaran','Total Harga'];const data=rows.map(r=>[r.transaction_no,r.transaction_date,categoryName(r.category_code),r.item_name_snapshot,r.qty,r.unit||'',state.payments.find(p=>p.code===r.payment_code)?.name||r.payment_code,r.total_price]);const csv=[head,...data].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`bakul-sayur-riwayat-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function loadMaster(){const q=$('#master-search')?.value.trim().toLowerCase()||'',cat=$('#master-category')?.value||'';const rows=state.items.filter(i=>(!cat||i.category_code===cat)&&(!q||`${i.legacy_item_id||''} ${i.name}`.toLowerCase().includes(q)));$('#master-body').innerHTML=rows.map(i=>`<tr><td>${escapeHtml(i.legacy_item_id||'—')}</td><td><strong>${escapeHtml(i.name)}</strong></td><td><span class="badge">${escapeHtml(categoryName(i.category_code))}</span></td><td>${escapeHtml(i.unit_default||'—')}</td><td><span class="badge success">Aktif</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Item tidak ditemukan.</td></tr>';const counts=state.categories.map(c=>({name:c.name,n:state.items.filter(i=>i.category_code===c.code).length}));$('#master-summary').innerHTML=counts.map(c=>`<div class="mini-kpi"><span>${escapeHtml(c.name.toUpperCase())}</span><strong>${c.n}</strong></div>`).join('')}
async function addItem(e){e.preventDefault();try{if(!navigator.onLine)throw new Error('Tambah master item membutuhkan koneksi internet. Transaksi dengan item yang sudah ada tetap bisa dicatat offline.');const cat=$('#new-item-category').value,name=$('#new-item-name').value.trim(),unit=$('#new-item-unit').value.trim()||'';const existing=state.items.some(i=>i.category_code===cat&&i.name.trim().toLowerCase()===name.toLowerCase());if(existing)throw new Error('Item dengan nama tersebut sudah ada pada kategori ini.');const created=await apiCall('create_item',{categoryCode:cat,name,unitDefault:unit});const item=Array.isArray(created)?created[0]:created;if(item)state.items.push(item);$('#item-dialog').close();e.target.reset();populateSelects();loadMaster();toast('Item baru berhasil ditambahkan.')}catch(err){toast(err.message,true)}}
function bind(){const hs=debounce(()=>loadHistory(true),240);$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=$('#login-btn');if(b.disabled)return;b.disabled=true;b.classList.add('is-loading');try{await login($('#login-pin').value);$('#login-view').classList.add('hidden');$('#app').classList.remove('hidden');$('#login-pin').value='';await bootstrap();const p=new URLSearchParams(location.search).get('page');if(p)navigate(p)}catch(err){toast(err.message,true);$('#login-pin').select()}finally{b.disabled=false;b.classList.remove('is-loading')}});$('[data-page]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navigate(b.dataset.page)}));$('#logout-btn').addEventListener('click',()=>logout());$('#refresh-dashboard').addEventListener('click',()=>loadDashboard(true));$('#dashboard-month').addEventListener('change',()=>loadDashboard());$('#expense-category').addEventListener('change',filterExpenseItems);$('#expense-item-search').addEventListener('input',debounce(filterExpenseItems,100));$('#expense-item').addEventListener('change',()=>{const it=state.items.find(i=>i.id===$('#expense-item').value);if(it?.unit_default)$('#expense-unit').value=it.unit_default});$('#expense-total').addEventListener('input',e=>{const n=e.target.value.replace(/\D/g,'');e.target.value=n?new Intl.NumberFormat('id-ID').format(Number(n)):''});$('#expense-form').addEventListener('submit',saveExpense);$('#history-search').addEventListener('input',hs);$('#history-category').addEventListener('change',()=>loadHistory(true));$('#history-date').addEventListener('change',()=>{loadHistory(true);window.loadHistorySummary?.()});$('#history-reset').addEventListener('click',()=>{$('#history-search').value='';$('#history-category').value='';$('#history-date').value='';loadHistory(true);window.loadHistorySummary?.()});$('#history-prev').addEventListener('click',()=>{if(state.historyPage>0){state.historyPage--;loadHistory()}});$('#history-next').addEventListener('click',()=>{state.historyPage++;loadHistory()});$('#export-csv').addEventListener('click',exportCsv);$('#master-search').addEventListener('input',debounce(loadMaster,120));$('#master-category').addEventListener('change',loadMaster);$('#open-add-item').addEventListener('click',()=>$('#item-dialog').showModal());$('#close-dialog').addEventListener('click',()=>$('#item-dialog').close());$('#cancel-item').addEventListener('click',()=>$('#item-dialog').close());$('#add-item-form').addEventListener('submit',addItem);$('[data-install-app]').forEach(b=>b.addEventListener('click',handleInstall));$('#close-install-dialog')?.addEventListener('click',()=>$('#install-dialog').close());bindInstallEvents()}
async function init(){registerServiceWorker();bind();window.addEventListener('online',()=>{updateConnectionStatus();syncPending()});window.addEventListener('offline',updateConnectionStatus);await updateConnectionStatus();state.session=getSession();const valid=state.session?.token&&state.session?.expiresAt&&new Date(state.session.expiresAt)>new Date();if(valid){$('#login-view').classList.add('hidden');$('#app').classList.remove('hidden');try{await bootstrap();const p=new URLSearchParams(location.search).get('page');if(p)navigate(p);if(navigator.onLine)syncPending()}catch(e){toast(e.message,true);if(navigator.onLine)clearSession(false)}}else{clearSession(false);setTimeout(()=>$('#login-pin')?.focus(),80)}}
init();
